### ISSUE TITLE
Support of FontAwesome Pro

### ISSUE THREAD

**Issue by efinder2** [ravi8x/Android-Font-Awesome#4]
Please support FontAwesome Pro. I know it would be difficult cause the user have to use his own fonts but it would be possbile to work with it more freely. 

Thanks for your great work until now.

**Comment by ravi8x** [comment]
FontAwesome Pro package should be bought individually. I shouldn't buy one and make it public.

**Comment by efinder2** [comment]
Yes I know but you may add functionality to use these Font Types. The user need to buy his license on his own. And add the font to a specified folder and use it via your great API
